//! The instruction channel: what the inductor calls when it pushes work.
//!
//! This is the inverted half of the protocol. Until now a worker *pulled* — it
//! registered, polled `/api/task` for an offer, and posted its own heartbeat —
//! which meant every worker needed a route to the inductor, and the inductor
//! needed to be reachable. That is fine on a LAN and impossible across NAT: a
//! cloud box cannot dial a laptop.
//!
//! The inductor already dials every worker over SSH (provisioning, launching,
//! sweeping), so making it dial for work too **removes** a requirement instead
//! of trading one. Nothing has to reach the inductor, so there is no tunnel to
//! build and no port to expose.
//!
//! It also fixes a contradiction the code already had: `state.rs` opens with
//! "Workers report facts; this decides", but a pull transport lets the worker
//! decide *when* to ask. Here the inductor decides everything and the worker
//! answers.
//!
//! ## The endpoints
//!
//! * `GET /status` — the worker's own [`Heartbeat`]. Same type the pull
//!   protocol posts, so the inductor's liveness bookkeeping and the panes are
//!   unchanged; only who asks has moved.
//! * `POST /task` — run one [`TaskOffer`], answer with the [`Complete`]. Held
//!   for as long as the stage takes, so dropping the connection is a cancel.
//! * `GET /units` — drain the render units produced so far. This is the one
//!   that has to exist for the inversion to be complete: a render uploads wavs
//!   *as it produces them* today (`upload_segment`), and that is a worker→
//!   inductor call. Pulling them keeps the streaming — a crash mid-render still
//!   leaves everything already rendered — where folding them into the final
//!   answer would lose the lot.
//!
//! ## Authentication
//!
//! Required, on every request, from day one. The pull protocol asked workers
//! *questions*; this one hands them **instructions**, and an unauthenticated
//! instruction channel is a box that renders whatever a stranger who can reach
//! the port asks for. The token is the cluster's own (`bm_core::token`),
//! generated by the inductor and shipped to the worker's root by provisioning —
//! never on a command line, because a secret in `argv` is a secret in `ps`.
//!
//! A worker with no token **refuses to serve at all** rather than serving
//! openly. "Authenticated or off" is the only safe pair of states.

use crate::{
    clear_task, heartbeat_now, run_offer, set_task, LoadProbe, PolicyRefusal, Shared, Sidecar,
    TaskResult, WorkerIdentity,
};
use axum::{
    body::Body,
    extract::{Query, State},
    http::{HeaderMap, StatusCode},
    response::{IntoResponse, Response},
    routing::{get, post},
    Json, Router,
};
use bm_core::{config::Settings, Layout};
use bm_proto::{Complete, Heartbeat, TaskOffer};
use serde::Deserialize;
use std::sync::{
    atomic::{AtomicBool, AtomicU64, Ordering},
    Arc, Mutex,
};
use std::time::Duration;

/// Sentinel for [`Push::tts_threads`]: no inductor instruction, so the
/// sidecar's own default (or `BM_TTS_THREADS`) stands.
pub(crate) const THREADS_UNSET: u64 = u64::MAX;

/// What the server needs to answer: who this worker is, what it is doing, and
/// everything a pushed task needs in order to run.
pub(crate) struct Push {
    pub(crate) who: WorkerIdentity,
    /// The cluster token. Required on every request.
    pub(crate) token: String,
    pub(crate) shared: Shared,
    /// Sampling state for the status answer — the CPU delta needs the previous
    /// reading, so it cannot be rebuilt per request.
    pub(crate) probe: Mutex<LoadProbe>,
    pub(crate) layout: Layout,
    pub(crate) settings: Settings,
    /// The sidecar, warm across tasks and bounded by its own lifecycle rules —
    /// an idle reap (`sidecar_reaper`), a budget recycle at each task boundary
    /// (`Sidecar::recycle_if_over_budget`), and `reap_all` before a merge.
    ///
    /// `tokio::sync::Mutex`, not `std::sync`'s: `run_offer` takes `&mut` and is
    /// awaited while the guard is held, and a `std::sync::MutexGuard` across an
    /// `await` makes the whole future non-`Send` — which axum reports as an
    /// opaque "`Handler` is not satisfied".
    pub(crate) sidecar: tokio::sync::Mutex<Sidecar>,
    /// One task at a time, which is what the pull protocol's single task slot
    /// gave too. A second `POST /task` while one runs gets 409 rather than a
    /// queue: the inductor owns the schedule, and a worker holding a backlog is
    /// a worker whose lease the inductor cannot reason about.
    pub(crate) busy: AtomicBool,
    /// Unix seconds of the last request the inductor made.
    ///
    /// The idle watchdog's only input. In serve-only mode there is no dial to
    /// fail and no report to be refused, so silence is the only evidence that
    /// the inductor is gone.
    pub(crate) last_contact: AtomicU64,
    /// Unix seconds the last task finished. The sidecar reaper stops the warm
    /// model once this is older than its idle budget — the sidecar is kept
    /// warm *between* tasks, not forever.
    pub(crate) last_task_end: AtomicU64,
    /// Whether this worker should keep a TTS sidecar at all. **`true` is the
    /// default and the invariant:** every render task runs on the assumption
    /// that a sidecar may be ensured, so the flag may only be cleared by an
    /// explicit instruction from the inductor (`POST /sidecar-policy`) and
    /// must be restored before any render is accepted again — which
    /// [`Sidecar::allow_ensure`]/[`Sidecar::require_allowed`] enforce.
    ///
    /// The inductor sets it when the operator turns `render` off in a box's
    /// work policy, and restores it when render comes back on: the policy is
    /// the operator's decision, and the sidecar is just the consequence —
    /// the worker's own idle reaper and memory guard keep applying either
    /// way. `AtomicBool` rather than inside the sidecar's mutex so the reaper
    /// and the endpoint can read it without contending on that lock.
    pub(crate) keep_sidecar: AtomicBool,
    /// The ONNX thread count the inductor pushed for this box's sidecar, as
    /// [`THREADS_UNSET`] when it has no opinion. An atomic for the same reason
    /// `keep_sidecar` is one: `POST /sidecar-policy` must answer without
    /// waiting on the sidecar's mutex, which a running render holds.
    pub(crate) tts_threads: AtomicU64,
    /// Data-plane dial-out, and only that: the reverse tunnel's worker-side
    /// end (`http://127.0.0.1:{hook port}`), which *is* the inductor's control
    /// API while the inductor holds the tunnel open. A merge pulls the take
    /// files it lacks through it; scheduling still never asks. Empty where
    /// the tunnel is not expected, and a down tunnel fails the pull loudly
    /// rather than mixing a partial chapter.
    pub(crate) fetch_http: reqwest::Client,
    pub(crate) fetch_base: String,
}

/// A task outcome, stored where the completion hook can find it.
///
/// `run_offer` already ships every artifact as it produces them (units ride
/// with the report, the merge's mp3 comes home in it) — so the only thing a
/// dead uplink loses is the word *done*. The task handler stashes the whole
/// report right after building it, and then answers on the connection that
/// asked, exactly as before. The stash costs nothing while the primary
/// channel is healthy (the hook sends it only after long inductor silence —
/// see `hook::supervise`) and is the difference between a finished stage and
/// a re-rendered one when the uplink blips mid-task.
fn stash_outcome(push: &Push, report: &Complete) {
    if let Ok(mut p) = push.shared.lock() {
        p.pending = Some(report.clone());
    }
}

impl Push {
    /// Note that the inductor just spoke to us.
    pub(crate) fn touch(&self) {
        self.last_contact
            .store(bm_proto::now_secs(), Ordering::SeqCst);
    }

    /// Whether a render on this box may start its sidecar.
    pub(crate) fn keep_sidecar(&self) -> bool {
        self.keep_sidecar.load(Ordering::SeqCst)
    }

    /// Record the inductor's instruction about the sidecar. The idle reaper
    /// stops the warm model as soon as it is idle either way — the answer is
    /// deliberately the same in both directions, so the sidecar's remaining
    /// life never depends on who asked.
    pub(crate) fn set_keep_sidecar(&self, keep: bool) {
        self.keep_sidecar.store(keep, Ordering::SeqCst);
    }

    /// The thread count the inductor asked for, or `None` for "no opinion".
    pub(crate) fn tts_threads_desired(&self) -> Option<u32> {
        let v = self.tts_threads.load(Ordering::SeqCst);
        (v != THREADS_UNSET).then_some(v as u32)
    }

    /// Record the inductor's thread instruction. `None` clears it, restoring
    /// the sidecar's own default.
    pub(crate) fn set_tts_threads(&self, threads: Option<u32>) {
        self.tts_threads.store(
            threads.map(u64::from).unwrap_or(THREADS_UNSET),
            Ordering::SeqCst,
        );
    }

    pub(crate) fn is_busy(&self) -> bool {
        self.busy.load(Ordering::SeqCst)
    }

    /// How long the inductor has been silent.
    pub(crate) fn silent_for(&self) -> Duration {
        let last = self.last_contact.load(Ordering::SeqCst);
        Duration::from_secs(bm_proto::now_secs().saturating_sub(last))
    }
}

/// The router the inductor talks to.
pub(crate) fn router(push: Arc<Push>) -> Router {
    Router::new()
        .route("/status", get(status))
        .route("/task", post(task))
        .route("/unit", get(unit))
        .route("/sidecar-policy", post(sidecar_policy))
        .route("/shutdown", post(shutdown))
        .with_state(push)
}

/// `GET /status` — the worker's heartbeat, on request instead of on a timer.
///
/// One builder for both directions (`heartbeat_now`), so the answer here and the
/// beat the pull protocol posts cannot drift apart.
async fn status(
    State(push): State<Arc<Push>>,
    headers: HeaderMap,
) -> Result<Json<Heartbeat>, (StatusCode, String)> {
    check(&headers, &push.token)?;
    push.touch();
    let p = push.shared.lock().map(|p| p.clone()).unwrap_or_default();
    let mut probe = push
        .probe
        .lock()
        .map_err(|_| (StatusCode::INTERNAL_SERVER_ERROR, "probe poisoned".into()))?;
    // The worker's own sidecar belief travels in the beat: the dispatcher's
    // convergence knows what it *told* this box, but only this answer says
    // what the box actually believes — which is what a reboot resets.
    let keep = push.keep_sidecar();
    // Told the same way, and read back by the dispatcher's convergence: the
    // thread count is the second half of the sidecar instruction.
    let threads = push.tts_threads_desired();
    Ok(Json(heartbeat_now(
        &p, &push.who, &mut probe, keep, threads,
    )))
}

/// `Authorization: Bearer <token>`, compared without short-circuiting.
///
/// One header, one shape, every endpoint: a per-endpoint scheme is how a
/// forgotten check becomes a public one. Returns a `Result` rather than a
/// `bool` so a handler cannot forget it — the compiler asks.
fn check(headers: &HeaderMap, token: &str) -> Result<(), (StatusCode, String)> {
    let unauthorised = || {
        (
            StatusCode::UNAUTHORIZED,
            "missing or wrong cluster token".to_string(),
        )
    };
    let Some(value) = headers.get(axum::http::header::AUTHORIZATION) else {
        return Err(unauthorised());
    };
    let Ok(text) = value.to_str() else {
        return Err(unauthorised());
    };
    match text.strip_prefix("Bearer ") {
        Some(presented) if bm_core::token::matches(presented.trim(), token) => Ok(()),
        _ => Err(unauthorised()),
    }
}

/// `POST /task` — run one offer and answer with its `Complete`.
///
/// The response is held for as long as the stage takes, so the inductor learns
/// the outcome on the connection it used to ask. That also makes dropping the
/// connection a cancel, which the pull protocol had no way to express.
async fn task(
    State(push): State<Arc<Push>>,
    headers: HeaderMap,
    Json(offer): Json<TaskOffer>,
) -> Response {
    if let Err(e) = check(&headers, &push.token) {
        return e.into_response();
    }
    push.touch();
    // `swap` rather than load-then-store: two simultaneous posts must not both
    // find the slot free.
    if push.busy.swap(true, Ordering::SeqCst) {
        let running = push
            .shared
            .lock()
            .map(|p| p.task_id.clone().unwrap_or_default())
            .unwrap_or_default();
        return (StatusCode::CONFLICT, format!("already running {running}")).into_response();
    }
    let _guard = BusyGuard {
        busy: &push.busy,
        shared: &push.shared,
    };
    // Tell the status answer what this worker is doing. The pull path sets
    // this before `run_offer`; without it `/status` answers `task_id: None`
    // while a render is at 45%, the inductor reads that as "idle", and its own
    // orphan pass then requeues the very task the worker is executing.
    set_task(&push.shared, &offer);

    let mut sidecar = push.sidecar.lock().await;
    // The inductor URL is deliberately empty: units stay on this box and the
    // inductor collects them (`GET /unit`). Any code path that tried to dial
    // out would fail loudly here rather than silently depending on a route
    // that does not exist across NAT — which is the whole reason for the
    // inversion. The one exception is the completion hook (`hook.rs`), whose
    // address is the inductor's own reverse tunnel and which fires only when
    // the inductor has gone silent — a backup channel, never a rival to this
    // answer.
    //
    // A merge here mixes local pieces plus whatever it pulls through the
    // reverse tunnel (`fetch_*`): a box behind NAT cannot be handed pieces
    // any other way, so a merge offered here runs where the audio already
    // is or fails loudly by name.
    let started = std::time::Instant::now();
    // The sidecar policy as of **before** the offer: a snapshot, not a read
    // the stage could see move under it. `false` is the inductor's
    // instruction (the operator turned render off) — the render arm refuses
    // with a typed error that becomes a 403 below, strike-free on the
    // inductor's side, instead of re-warming the model against the policy.
    let keep_sidecar = push.keep_sidecar();
    let tts_threads = push.tts_threads_desired();
    let result = run_offer(
        &push.layout,
        &push.settings,
        &offer,
        &push.shared,
        &mut sidecar,
        Some((&push.fetch_http, push.fetch_base.as_str())),
        keep_sidecar,
        tts_threads,
    )
    .await;
    // Deliberately **no** `sidecar.stop()` here: the sidecar is worker-owned
    // and stays warm across tasks (a per-take schedule would otherwise reload
    // ~2.85 GB per offer). `sidecar_reaper` stops it after the idle budget, and
    // the merge arm stops it before ffmpeg runs.
    //
    // Idle again, whatever the outcome — the answer below is built from
    // `result`, so nothing past this point needs the progress block.
    clear_task(&push.shared);

    // A render refused because the operator turned render off is **not a
    // stage failure**: the inductor's `run_one` answers it with a strike-free
    // release of the covered rows (the same rule a lease expiry gets), while
    // a 200 `ok:false` report would cost the chapter one of its three
    // strikes — three operator policy flips in a row would shelve a chapter
    // for a decision the operator made. 403 is the one status the dispatcher
    // treats as "refused, not failed"; everything else keeps its old shape.
    let refused = result.as_ref().err().is_some_and(|e| {
        e.chain()
            .any(|c| c.downcast_ref::<PolicyRefusal>().is_some())
    });
    if refused {
        return (
            StatusCode::FORBIDDEN,
            "render refused: this box's policy turns render off".to_string(),
        )
            .into_response();
    }
    push.last_task_end
        .store(bm_proto::now_secs(), Ordering::SeqCst);

    match result {
        // Destructure once: the stash and the response are the same report,
        // and `Complete` clones would deep-copy a merge mp3 for nothing.
        Ok(done) => {
            let TaskResult {
                ok,
                detail,
                delta,
                units,
                script,
                text,
                crawl,
                mp3_b64,
                unit_files,
            } = done;
            let report = Complete {
                worker_id: push.who.worker_id.clone(),
                task_id: offer.task_id.clone(),
                ok,
                detail,
                duration_secs: started.elapsed().as_secs_f64(),
                bible_delta: delta,
                units,
                script,
                text,
                crawl,
                mp3_b64,
                unit_files,
            };
            // Stash before answering: if the connection below dies in flight,
            // this outcome is the only copy on earth (well — and on this
            // disk, for renders). The hook delivers it when silence says the
            // inductor never heard the answer.
            stash_outcome(&push, &report);
            Json(report).into_response()
        }
        // A stage that *failed* is an answer, not a transport error — and the
        // pull path reports it exactly this way. A 500 here would make the
        // inductor read a text body as a `Complete` and give up on a task the
        // worker had in fact finished failing, leaving the chapter assigned
        // until its lease expired.
        Err(e) => {
            let report = Complete {
                worker_id: push.who.worker_id.clone(),
                task_id: offer.task_id.clone(),
                ok: false,
                detail: format!("{} ch{} failed: {e:#}", offer.stage, offer.chapter),
                duration_secs: started.elapsed().as_secs_f64(),
                bible_delta: None,
                units: 0,
                script: None,
                text: None,
                // The failure path has no verdict to carry: the error text
                // above is the diagnosis, and an unclassified failure takes
                // the ordinary strike ladder.
                crawl: None,
                mp3_b64: None,
                unit_files: Vec::new(),
            };
            stash_outcome(&push, &report);
            Json(report).into_response()
        }
    }
}

/// Clears the busy flag AND the shared task slot however the handler leaves —
/// including when a dropped POST cancels this future mid-task.
///
/// That cancel is not hypothetical: the inductor aborts a losing digest
/// racer's POST once another box wins, and a dead link does the same. The
/// explicit `clear_task` at the end of the handler never runs then, so
/// without this the worker would report busy on a dead task for ever — the
/// drive reads `task_id` to decide idleness and never offers new work.
/// (A panic in a task body gets the same rescue, as before.)
struct BusyGuard<'a> {
    busy: &'a AtomicBool,
    shared: &'a Shared,
}

impl Drop for BusyGuard<'_> {
    fn drop(&mut self) {
        self.busy.store(false, Ordering::SeqCst);
        clear_task(self.shared);
    }
}

#[derive(Deserialize)]
struct UnitQuery {
    chapter: u32,
    engine: String,
    name: String,
}

/// `GET /unit` — one rendered wav, from this worker's own segment directory.
///
/// **The inductor asks for what it knows it is missing**, so this needs no
/// ledger, no acknowledgement and no lease: a transfer that fails simply means
/// the next pass asks again, and a name the inductor already holds is never
/// requested. Folding the units into the task's final answer instead would mean
/// a render that crashes at unit 49 of 50 returns nothing, where this returns
/// the 48 that finished.
async fn unit(
    State(push): State<Arc<Push>>,
    headers: HeaderMap,
    Query(q): Query<UnitQuery>,
) -> Response {
    if let Err(e) = check(&headers, &push.token) {
        return e.into_response();
    }
    push.touch();
    // The name arrives from the network, so it is checked before it is joined:
    // `../../etc/passwd` is a legal-looking filename and `join` would happily
    // walk out of the segment directory with it.
    if !safe_unit_name(&q.name) {
        return (
            StatusCode::BAD_REQUEST,
            format!("bad unit name {:?}", q.name),
        )
            .into_response();
    }
    let path = push.layout.seg_dir(&q.engine, q.chapter).join(&q.name);
    match tokio::fs::read(&path).await {
        Ok(bytes) => Response::builder()
            .status(StatusCode::OK)
            .header("content-type", "audio/wav")
            .body(Body::from(bytes))
            .unwrap_or_else(|_| StatusCode::INTERNAL_SERVER_ERROR.into_response()),
        // Absent is not an error: this worker does not have that unit — another
        // box rendered it, or this render has not reached it yet.
        Err(_) => (StatusCode::NOT_FOUND, format!("no {}", q.name)).into_response(),
    }
}

/// The body of `POST /sidecar-policy`.
#[derive(Deserialize)]
struct SidecarPolicyUpdate {
    keep: bool,
    /// The ONNX thread count to open the sidecar with; omitted/`null` means
    /// "no opinion" (the sidecar's own default). Older agents ignore it.
    #[serde(default)]
    threads: Option<u32>,
}

/// `POST /sidecar-policy` — a policy consequence, not a policy.
///
/// See the module comment above for the contract; this is its one endpoint.
/// Answering **before** the model actually stops keeps the inductor's view of
/// its next render decision exact without holding the connection for the
/// shutdown waits, and without promising a model that is already leaving.
async fn sidecar_policy(
    State(push): State<Arc<Push>>,
    headers: HeaderMap,
    Json(u): Json<SidecarPolicyUpdate>,
) -> Response {
    if let Err(e) = check(&headers, &push.token) {
        return e.into_response();
    }
    push.touch();
    push.set_keep_sidecar(u.keep);
    push.set_tts_threads(u.threads);
    if u.keep {
        println!("sidecar policy: keep — the next render may ensure it again");
    } else {
        println!(
            "sidecar policy: do not keep — the idle reaper stops it as soon as this worker is idle"
        );
    }
    // Answered without touching the sidecar's mutex on purpose: a render
    // holds that lock for its whole duration, and an ack that waits behind it
    // would outlive the inductor's timeout and be retried forever. The flag
    // is stored already; whether a model is resident right now is the reaper's
    // business, visible in the next beat's `sidecars` census.
    Json(serde_json::json!({"ok": true})).into_response()
}

/// `POST /shutdown` — exit on the inductor's say-so.
///
/// The pull protocol carried this as a latch on the heartbeat *answer*; the
/// inverted direction has no answer to hang it on, so the command travels as
/// its own request. The reply goes out first — the inductor should learn that
/// the worker accepted rather than guess from a closed socket — and the exit
/// is deliberate rather than a drop, so the port is released promptly.
async fn shutdown(State(push): State<Arc<Push>>, headers: HeaderMap) -> Response {
    if let Err(e) = check(&headers, &push.token) {
        return e.into_response();
    }
    push.touch();
    println!("inductor asked for shutdown — exiting");
    // Take the sidecar with us: a child left behind is 2.85 GB held by a box
    // nobody is driving, and a spot reclaim leaves one behind every time.
    // `reap_all`, not `stop`: the provision-started server is nobody's child, and
    // leaving *it* resident is the same orphan by another route. The HTTP ask is
    // best-effort — an older sidecar has no `/shutdown`, and the cluster sweep
    // (`X`) is the backstop for one that declined.
    push.sidecar.lock().await.reap_all().await;
    tokio::spawn(async {
        tokio::time::sleep(Duration::from_millis(250)).await;
        std::process::exit(0);
    });
    Json(serde_json::json!({"ok": true, "exiting": true})).into_response()
}

/// How long the warm model is kept after the last task. Long enough to bridge
/// consecutive render offers on one box, short enough that an idle box is not
/// holding 2.85 GB.
const SIDECAR_IDLE_SECS: u64 = 180;

/// Stop the sidecar once the worker has been idle past [`SIDECAR_IDLE_SECS`].
///
/// This is what makes "keep it warm" safe: the model lives across tasks, not
/// across hours. A task arriving resets the clock, and a later render re-`ensure`s
/// a stopped sidecar (waiting for it, never racing it).
///
/// **This is the idle half of the lifecycle, and only the idle half.** A box
/// that renders continuously never reaches this branch — which is exactly how
/// the memory leak went unnoticed, since the guard that existed was keyed on
/// *not working*. Growth under load is `Sidecar::recycle_if_over_budget`'s job,
/// and it runs at a task boundary inside the render arm where it cannot
/// interrupt a request. Neither replaces the other: this one bounds an idle
/// box's footprint, that one bounds a busy box's.
///
/// **Deliberately `stop`, not `reap_all`.** An *adopted* server is somebody
/// else's to keep: on the local node the inductor uses the same port 8818 for
/// auditions, and reaping on this worker's idle timer would kill a model the
/// operator is listening to. The two places that really cannot share the box —
/// a merge's ffmpeg pass, and worker shutdown — call `reap_all` themselves, so
/// nothing depends on this timer for the memory they need.
pub(crate) async fn sidecar_reaper(push: Arc<Push>) {
    loop {
        tokio::time::sleep(Duration::from_secs(30)).await;
        if push.is_busy() {
            continue;
        }
        let idle = bm_proto::now_secs().saturating_sub(push.last_task_end.load(Ordering::SeqCst));
        if idle < SIDECAR_IDLE_SECS {
            continue;
        }
        // The policy is checked **inside** the lock and before `is_running`,
        // so a flag flip racing this tick cannot stop the model twice, and a
        // `do not keep` instruction is honoured at most 30 s after it lands —
        // even on a box that renders continuously, which the idle branch
        // alone would never reach. The lifecycle stays the same in both
        // directions: a re-warm is a render's business (a `keep` instruction
        // restores it), and this is the *stopping* half.
        let mut sidecar = push.sidecar.lock().await;
        if !push.keep_sidecar() {
            if sidecar.is_running() {
                sidecar.stop();
                println!("sidecar stopped — the policy says this box keeps none");
            }
            continue;
        }
        if sidecar.is_running() {
            sidecar.stop();
            println!("sidecar stopped after {idle}s idle — its RSS returns to the OS");
            continue;
        }
        // An adopted server nobody owns: provisioning's boot-time instance,
        // still answering long after the worker that used it moved on. The
        // owned branch above never reaches it (`stop` only signals our own
        // child), the render-boundary recycle never runs while no renders
        // arrive, and the inductor's 90% memory guard withholds new work from
        // a full box — so a fat idle server parks its box for ever: too full
        // to work, nothing clearing while idle. Reap it once it is both idle
        // and over budget; the next render re-ensures a fresh server this
        // worker owns, which the owned branch then manages.
        //
        // Non-local boxes only: on the local node the same port serves the
        // operator's auditions, and killing an adopted server mid-listen is
        // the tradeoff the owned-only rule was written to avoid.
        if !bm_core::is_local_node(&push.who.addr) {
            if let Some(why) = sidecar.over_budget() {
                println!("adopted sidecar {why} — reaping it so this box drains");
                sidecar.reap_all().await;
            }
        }
    }
}

/// A unit name is one stored take's filename and nothing else.
///
/// The renderer names takes `t-<take_key>.wav` or `t-<take_key>.mp3` — the
/// extension is the storage tier's ([`bm_core::assemble::TAKE_EXTENSIONS`]), so
/// both are ours; an adopted take keeps its legacy `0007_Voice.wav` shape.
/// Anything with a separator, a parent reference or an absolute prefix is not
/// one of ours and must never reach `Path::join`.
///
/// **The extension check reads the shared list, not a literal.** A `.wav`-only
/// guard here refused every `.mp3` take the moment the default tier stopped
/// being raw PCM, so `GET /unit` answered 400 and a remote render's takes never
/// came home — the chapter failed its completion gate while the audio sat on
/// the worker's disk.
fn safe_unit_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() < 256
        && std::path::Path::new(name)
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| bm_core::assemble::TAKE_EXTENSIONS.contains(&e))
        && !name.contains('/')
        && !name.contains('\\')
        && !name.contains('\0')
        && !name.starts_with('.')
}

#[cfg(test)]
mod tests;
