//! The instruction channel: what the inductor calls when it pushes work.
//!
//! This is the inverted half of the protocol. Until now a worker *pulled* — it
//! registered, polled `/api/task` for an offer, and posted its own heartbeat —
//! which meant every worker needed a route to the inductor, and the inductor
//! needed to be reachable. That is fine on a LAN and impossible across NAT: a
//! cloud box cannot dial a laptop.
//!
//! The inductor already dials every worker over SSH (provisioning, launching,
//! sweeping), so making it dial for work too **removes** a requirement instead
//! of trading one. Nothing has to reach the inductor, so there is no tunnel to
//! build and no port to expose.
//!
//! It also fixes a contradiction the code already had: `state.rs` opens with
//! "Workers report facts; this decides", but a pull transport lets the worker
//! decide *when* to ask. Here the inductor decides everything and the worker
//! answers.
//!
//! ## The endpoints
//!
//! * `GET /status` — the worker's own [`Heartbeat`]. Same type the pull
//!   protocol posts, so the inductor's liveness bookkeeping and the panes are
//!   unchanged; only who asks has moved.
//! * `POST /task` — run one [`TaskOffer`], answer with the [`Complete`]. Held
//!   for as long as the stage takes, so dropping the connection is a cancel.
//! * `GET /units` — drain the render units produced so far. This is the one
//!   that has to exist for the inversion to be complete: a render uploads wavs
//!   *as it produces them* today (`upload_segment`), and that is a worker→
//!   inductor call. Pulling them keeps the streaming — a crash mid-render still
//!   leaves everything already rendered — where folding them into the final
//!   answer would lose the lot.
//!
//! ## Authentication
//!
//! Required, on every request, from day one. The pull protocol asked workers
//! *questions*; this one hands them **instructions**, and an unauthenticated
//! instruction channel is a box that renders whatever a stranger who can reach
//! the port asks for. The token is the cluster's own (`bm_core::token`),
//! generated by the inductor and shipped to the worker's root by provisioning —
//! never on a command line, because a secret in `argv` is a secret in `ps`.
//!
//! A worker with no token **refuses to serve at all** rather than serving
//! openly. "Authenticated or off" is the only safe pair of states.

use crate::{heartbeat_now, LoadProbe, Shared, WorkerIdentity};
use axum::{
    extract::State,
    http::{HeaderMap, StatusCode},
    routing::get,
    Json, Router,
};
use bm_proto::Heartbeat;
use std::sync::{Arc, Mutex};

/// What the server needs to answer: who this worker is, and what it is doing.
pub(crate) struct Push {
    pub(crate) who: WorkerIdentity,
    /// The cluster token. Required on every request.
    pub(crate) token: String,
    pub(crate) shared: Shared,
    /// Sampling state for the status answer — the CPU delta needs the previous
    /// reading, so it cannot be rebuilt per request.
    pub(crate) probe: Mutex<LoadProbe>,
}

/// The router the inductor talks to.
pub(crate) fn router(push: Arc<Push>) -> Router {
    Router::new().route("/status", get(status)).with_state(push)
}

/// `GET /status` — the worker's heartbeat, on request instead of on a timer.
///
/// One builder for both directions (`heartbeat_now`), so the answer here and the
/// beat the pull protocol posts cannot drift apart.
async fn status(
    State(push): State<Arc<Push>>,
    headers: HeaderMap,
) -> Result<Json<Heartbeat>, (StatusCode, String)> {
    if !authorised(&headers, &push.token) {
        return Err((
            StatusCode::UNAUTHORIZED,
            "missing or wrong cluster token".into(),
        ));
    }
    let p = push.shared.lock().map(|p| p.clone()).unwrap_or_default();
    let mut probe = push
        .probe
        .lock()
        .map_err(|_| (StatusCode::INTERNAL_SERVER_ERROR, "probe poisoned".into()))?;
    Ok(Json(heartbeat_now(&p, &push.who, &mut probe)))
}

/// `Authorization: Bearer <token>`, compared without short-circuiting.
///
/// One header, one shape, every endpoint: a per-endpoint scheme is how a
/// forgotten check becomes a public one.
fn authorised(headers: &HeaderMap, token: &str) -> bool {
    let Some(value) = headers.get(axum::http::header::AUTHORIZATION) else {
        return false;
    };
    let Ok(text) = value.to_str() else {
        return false;
    };
    match text.strip_prefix("Bearer ") {
        Some(presented) => bm_core::token::matches(presented.trim(), token),
        None => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Progress;

    fn push(token: &str) -> Arc<Push> {
        Arc::new(Push {
            who: WorkerIdentity {
                worker_id: "box-1".into(),
                addr: "192.168.2.2".into(),
                hostname: "box".into(),
                alias: "hawk".into(),
            },
            token: token.into(),
            shared: Arc::new(Mutex::new(Progress {
                task_id: Some("render:7".into()),
                stage: Some("render".into()),
                chapter: Some(7),
                frac: 0.5,
                activity: "render ch7".into(),
            })),
            probe: Mutex::new(LoadProbe::new()),
        })
    }

    fn headers(token: Option<&str>) -> HeaderMap {
        let mut h = HeaderMap::new();
        if let Some(t) = token {
            h.insert(
                axum::http::header::AUTHORIZATION,
                format!("Bearer {t}").parse().unwrap(),
            );
        }
        h
    }

    #[test]
    fn the_header_is_the_whole_gate() {
        // "Authenticated or off" is the only safe pair of states, and the check
        // is one shape for every endpoint — a per-endpoint scheme is how a
        // forgotten check becomes a public one.
        assert!(authorised(&headers(Some("s3cret")), "s3cret"));
        assert!(!authorised(&headers(None), "s3cret"), "no header, no entry");
        assert!(
            !authorised(&headers(Some("")), "s3cret"),
            "empty is not a token"
        );
        assert!(
            !authorised(&headers(Some("s3cres")), "s3cret"),
            "one byte off"
        );
        assert!(
            !authorised(&headers(Some("s3cretx")), "s3cret"),
            "a longer guess is not a match"
        );
        // Padding is tolerated, because some clients add it and trimming can
        // never turn a wrong token into a right one — it only removes bytes
        // from the ends.
        assert!(authorised(&headers(Some("s3cret ")), "s3cret"));
        assert!(authorised(&headers(Some(" s3cret")), "s3cret"));
        // A different scheme is not a bearer token.
        let mut h = HeaderMap::new();
        h.insert(
            axum::http::header::AUTHORIZATION,
            "Basic czNjcmV0".parse().unwrap(),
        );
        assert!(!authorised(&h, "s3cret"), "Basic is not Bearer");
    }

    #[tokio::test]
    async fn status_reports_the_worker_and_refuses_without_the_token() {
        // Over a real socket, because the gate's value is that it applies to the
        // route: testing `authorised` alone would pass with the handler never
        // wired up. `no_proxy` for the same reason the production clients use
        // it — an ambient HTTP_PROXY would answer for the loopback request and
        // this test would be asserting the shell's environment.
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        tokio::spawn(async move {
            let _ = axum::serve(listener, router(push("s3cret"))).await;
        });
        let http = reqwest::Client::builder().no_proxy().build().unwrap();
        let url = format!("http://{addr}/status");

        assert_eq!(http.get(&url).send().await.unwrap().status(), 401);
        assert_eq!(
            http.get(&url)
                .bearer_auth("nope")
                .send()
                .await
                .unwrap()
                .status(),
            401
        );

        let ok = http.get(&url).bearer_auth("s3cret").send().await.unwrap();
        assert_eq!(ok.status(), 200);
        let beat: Heartbeat = ok.json().await.unwrap();
        // The same fields the pull protocol's heartbeat carries, so the
        // inductor's bookkeeping and panes do not care which direction it came
        // from.
        assert_eq!(beat.worker_id, "box-1");
        assert_eq!(beat.addr, "192.168.2.2");
        assert_eq!(beat.alias, "hawk");
        assert_eq!(beat.chapter, Some(7));
        assert_eq!(beat.progress, 0.5);
        assert_eq!(beat.activity, "render ch7");
        assert!(beat.ts > 0);
    }
}
