//! JavaScript binding for the crawl ABI, on QuickJS.
//!
//! A second engine because the choice is genuinely an operator's: a site with a
//! `__NEXT_DATA__` blob or a JSON API is a dozen lines of JavaScript and a
//! fight in Lua, and the reverse is true for a listing walk. The *contract* is
//! identical, and so is every host function — the semantics live in
//! [`super::fns`], this file is only binding.
//!
//! ## Two decisions worth naming
//!
//! **The host ABI crosses as a JSON envelope.** Every `__bm_*` function takes
//! and returns strings: `{"ok": …}` or `{"err": "…"}`. That means no value
//! conversion between the two worlds, a host failure arrives in the script as a
//! normal `Error` it can `try/catch`, and there is no path where a Rust-side
//! conversion decides the meaning of a chapter.
//!
//! **`crawl` may be `async`.** An `async function crawl()` whose body is
//! synchronous (which every one is — `fetch` blocks) has a promise that
//! resolves as soon as the microtask queue runs, so the host pumps that queue
//! and reads the settled value. A promise that needs a *real* event loop is
//! refused with a message saying so, because the alternative — growing an event
//! loop inside a worker task — would take cancellation, leases and timeouts
//! with it.

use anyhow::{anyhow, Context, Result};
use rquickjs::context::EvalOptions;
use rquickjs::runtime::InterruptHandler;
use rquickjs::{CatchResultExt, Context as JsContext, Function, Runtime, Value as JsValue};
use serde_json::{json, Value};

use super::{fns, Entry, Program, SharedHost};

/// Bound on microtask draining. A resolved promise needs a handful; the cap is
/// what stops a `while (true) await tick()` from spinning here instead of in
/// the interrupt handler.
const MAX_PUMPS: usize = 100_000;

pub fn run(
    program: &Program,
    entry: Entry,
    host: SharedHost,
    input: &Value,
) -> Result<Option<Value>> {
    let name = program.name.clone();
    let rt = Runtime::new().context("creating a QuickJS runtime")?;
    {
        // The clock, from inside the interpreter: without it an
        // `while (true) {}` never reaches a host call and never dies.
        let h = host.clone();
        let handler: InterruptHandler =
            Box::new(move || h.try_borrow().map(|hh| !hh.budget_ok()).unwrap_or(false));
        rt.set_interrupt_handler(Some(handler));
    }
    let ctx = JsContext::full(&rt).context("creating a QuickJS context")?;
    ctx.with(|ctx| -> Result<Option<Value>> {
        let g = ctx.globals();
        bind(&ctx, &g, &host)?;
        g.set("__bm_input", serde_json::to_string(input)?)?;
        let options = || {
            let mut o = EvalOptions::default();
            // Not strict: an operator's one-file crawler is a script, not a
            // module, and strict mode would reject sloppy-mode habits for no
            // gain to anybody.
            o.strict = false;
            o.filename = Some(name.clone());
            o
        };
        ctx.eval_with_options::<JsValue, _>(PRELUDE, options())
            .catch(&ctx)
            .map_err(|e| anyhow!("{name}: binding the crawl host ABI failed: {e}"))?;
        // `.catch()` rather than the raw error: a syntax error in an operator's
        // script is the single most likely thing to happen here, and QuickJS's
        // bare `Error::Exception` says only "Exception generated by QuickJS"
        // while the caught value carries the message and the line number.
        ctx.eval_with_options::<JsValue, _>(program.source.clone(), options())
            .catch(&ctx)
            .map_err(|e| js_failure(&name, "loading the script", &e, &host))?;

        let status: String = ctx
            .eval_with_options::<rquickjs::String, _>(driver(entry), options())
            .catch(&ctx)
            .map_err(|e| js_failure(&name, entry.name(), &e, &host))?
            .to_string()?;
        if status == "absent" {
            return Ok(None);
        }
        if status == "pending" {
            // Drain the microtask queue: an `async function crawl` whose body
            // only calls synchronous host functions resolves here, and its
            // `.then` callback is one of these jobs.
            let mut pumps = 0usize;
            while pumps < MAX_PUMPS {
                if !host.try_borrow().map(|h| h.budget_ok()).unwrap_or(true) {
                    break;
                }
                if !ctx.execute_pending_job() {
                    break;
                }
                pumps += 1;
            }
        }
        let state = ctx
            .eval_with_options::<rquickjs::String, _>(
                "JSON.stringify(globalThis.__bm_state)",
                options(),
            )
            .catch(&ctx)
            .map_err(|e| anyhow!("{name}: reading the crawl result failed: {e}"))?
            .to_string()?;
        let state: Value = serde_json::from_str(&state)
            .map_err(|e| anyhow!("{name}: the crawl result was not readable: {e}"))?;
        match state.get("state").and_then(Value::as_str) {
            Some("ok") => Ok(state.get("value").cloned().filter(|v| !v.is_null())),
            Some("err") => Err(anyhow!(
                "{name}: {}() failed: {}",
                entry.name(),
                state
                    .get("error")
                    .and_then(Value::as_str)
                    .unwrap_or("no message")
            )),
            // Still pending after the pump: a promise that needs an event loop
            // of its own. Refused rather than waited on.
            _ => Err(anyhow!(
                "{name}: {}() returned a promise that never settled — the crawl host ABI is synchronous, so `await` on it resolves on the next microtask, not on I/O",
                entry.name()
            )),
        }
    })
}

/// The JSON envelope's counterpart, and the only JavaScript in this crate.
///
/// Every `__bm_*` function returns `{"ok": …}` or `{"err": …}`; unwrapping
/// here is what turns a Rust failure into a `try/catch`-able script error.
const PRELUDE: &str = r#"
(function () {
  function unwrap(raw) {
    var r = JSON.parse(raw);
    if (r && r.err !== undefined) { throw new Error(r.err); }
    return r ? r.ok : undefined;
  }
  globalThis.fetch = function (url, opts) {
    return unwrap(__bm_fetch(String(url), JSON.stringify(opts === undefined ? null : opts)));
  };
  globalThis.select = function (html, sel) {
    return unwrap(__bm_select(String(html), String(sel)));
  };
  globalThis.select_all = function (html, sel) {
    return unwrap(__bm_select_all(String(html), String(sel)));
  };
  globalThis.select_text = function (html, sel) {
    return unwrap(__bm_select_text(String(html), String(sel)));
  };
  globalThis.readable = function (html) { return unwrap(__bm_readable(String(html))); };
  globalThis.strip_tags = function (html) { return unwrap(__bm_strip_tags(String(html))); };
  globalThis.decode_entities = function (s) { return unwrap(__bm_decode_entities(String(s))); };
  globalThis.sanitize = function (s) { return unwrap(__bm_sanitize(String(s))); };
  globalThis.abs_url = function (b, h) { return unwrap(__bm_abs_url(String(b), String(h))); };
  globalThis.chapter_url = function (t, n) { return unwrap(__bm_chapter_url(String(t), String(n))); };
  globalThis.challenge = function (page) {
    return unwrap(__bm_challenge(JSON.stringify(page)));
  };
  globalThis.log = function (m) {
    __bm_log(typeof m === "string" ? m : JSON.stringify(m));
  };
})();
"#;

/// The driver: call the entry point, settle its promise, record the outcome.
fn driver(entry: Entry) -> String {
    let name = entry.name();
    format!(
        r#"
(function () {{
  if (typeof {name} !== "function") {{ return "absent"; }}
  var input = JSON.parse(__bm_input);
  var r;
  try {{
    r = {name}(input);
  }} catch (e) {{
    globalThis.__bm_state = {{ state: "err", error: String((e && e.message) || e) }};
    return "ok";
  }}
  if (r && typeof r.then === "function") {{
    globalThis.__bm_state = {{ state: "pending" }};
    r.then(
      function (v) {{ globalThis.__bm_state = {{ state: "ok", value: v }}; }},
      function (e) {{ globalThis.__bm_state = {{ state: "err", error: String((e && e.message) || e) }}; }}
    );
    return "pending";
  }}
  globalThis.__bm_state = {{ state: "ok", value: r }};
  return "ok";
}})()
"#
    )
}

/// A JavaScript failure, named.
///
/// The budget case is worth the special case: an interrupt is the one failure
/// QuickJS reports with no message at all, and "crawl() failed: Exception
/// generated by QuickJS" sends an operator looking at their selectors when the
/// real answer is a loop that never returns.
fn js_failure(
    name: &str,
    what: &str,
    e: &impl std::fmt::Display,
    host: &SharedHost,
) -> anyhow::Error {
    if host.try_borrow().map(|h| !h.budget_ok()).unwrap_or(false) {
        let secs = host
            .try_borrow()
            .map(|h| h.limits().max_seconds)
            .unwrap_or(0);
        return anyhow!(
            "{name}: {what} exceeded the crawl time budget ({secs}s) — a loop that never returns?"
        );
    }
    anyhow!("{name}: {what} failed: {e}")
}

/// Wrap a host result in the envelope the prelude unwraps.
fn envelope(out: Result<Value>) -> String {
    match out {
        Ok(v) => json!({ "ok": v }).to_string(),
        Err(e) => json!({ "err": format!("{e:#}") }).to_string(),
    }
}

/// The borrowed host, or an error describing why it was unavailable.
fn with_host<T>(host: &SharedHost, f: impl FnOnce(&mut super::super::host::Host) -> T) -> T {
    let mut h = host
        .try_borrow_mut()
        .expect("the crawl host is already borrowed (re-entrant host call?)");
    f(&mut h)
}

fn bind<'js>(ctx: &rquickjs::Ctx<'js>, g: &rquickjs::Object<'js>, host: &SharedHost) -> Result<()> {
    // Two host functions per call shape: the raw `__bm_*` returns the envelope,
    // the prelude's wrapper unwraps it. Deliberately `String`-in/`String`-out —
    // see the module docs.
    macro_rules! two_arg {
        ($name:literal, $call:expr) => {{
            let h = host.clone();
            let f = move |a: String, b: String| -> String {
                envelope(with_host(&h, |host| $call(host, &a, &b)))
            };
            g.set($name, Function::new(ctx.clone(), f)?)?;
        }};
    }
    macro_rules! one_arg {
        ($name:literal, $call:expr) => {{
            let h = host.clone();
            let f = move |a: String| -> String { envelope(with_host(&h, |host| $call(host, &a))) };
            g.set($name, Function::new(ctx.clone(), f)?)?;
        }};
    }

    two_arg!("__bm_fetch", |host, url, opts: &String| {
        let opts = if opts.trim().is_empty() {
            Value::Null
        } else {
            serde_json::from_str(opts).unwrap_or(Value::Null)
        };
        fns::fetch(host, url, opts)
    });
    two_arg!("__bm_select", fns::select);
    two_arg!("__bm_select_all", fns::select_all);
    two_arg!("__bm_select_text", fns::select_text);
    two_arg!("__bm_abs_url", |_host, base, href| Ok(fns::abs_url(
        base, href
    )));
    two_arg!("__bm_chapter_url", |_host, template, n: &String| {
        match n.trim().parse::<u32>() {
            Ok(n) => Ok(fns::chapter_url(template, n)),
            Err(_) => Err(anyhow!("chapter_url: {n:?} is not a chapter number")),
        }
    });
    one_arg!("__bm_readable", fns::readable);
    one_arg!("__bm_challenge", |_host, page: &String| {
        let page: Value = if page.trim().is_empty() {
            Value::Null
        } else {
            serde_json::from_str(page).unwrap_or(Value::Null)
        };
        // `None` becomes a real JS `null`, which is falsy — the shape a script
        // written as `if (challenge(r)) { … }` needs.
        fns::challenge(_host, page).map(|why| match why {
            Some(why) => Value::String(why),
            None => Value::Null,
        })
    });
    one_arg!("__bm_strip_tags", |_host, html| Ok(fns::strip_tags(html)));
    one_arg!("__bm_decode_entities", |_host, s| Ok(fns::decode_entities(
        s
    )));
    one_arg!("__bm_sanitize", |_host, s| Ok(fns::sanitize(s)));

    let h = host.clone();
    let log = Function::new(ctx.clone(), move |m: String| -> String {
        with_host(&h, |host| fns::log(host, &m));
        String::new()
    })?;
    g.set("__bm_log", log)?;

    // A selector parse failure and every other `anyhow` error surface as `err`
    // in the envelope, which the prelude throws — so nothing here returns
    // `Err`, and no Rust-side conversion can decide the meaning of a chapter.
    Ok(())
}
